### PR TITLE
Add a module for proving Stable with apalache

### PR DESCRIPTION
**Pull request by konnov**
This PR introduces `AsyncTerminationDetection_apalache.tla` that you can use to prove the property `Stable` with Apalache for `N=20`.

### CODE REVIEW

**Comment by lemmy** [comment]
Thanks, this creates a nice build-up to TLAPS. 

Merged with minor adjustments in https://github.com/lemmy/ewd998/commit/906e38c0da5edf98e69c04f538f1a5d44be9f2b3
* No `INSTANCE` statement, which students haven't seen yet (=> config file)
* Replace "prove" with "check" (reserving the term for TLAPS)

https://github.com/informalsystems/apalache/issues/468#issuecomment-853259723 causes a [minor dent](https://github.com/lemmy/ewd998/commit/5aecc8566f67b233b95c5e210614733349aca0c2#diff-93b69da75c6617e1ac70043729a26f79389e2a5b67db10ab3506bff6a3de135fL316). ;-p

**Comment by konnov** [comment]
I will fix https://github.com/informalsystems/apalache/issues/468#issuecomment-853259723. Re: INSTANCE, take care of the config files. You will need three files, unless you specify `--init` and `--next` in the command line.

**Comment by lemmy** [comment]
Partially, the tutorial checks itself:  https://github.com/lemmy/ewd998/runs/2730893015?check_suite_focus=true

**Comment by konnov** [comment]
Nice! Are you sure you need `libz3-jni`? We are using `z3-turnkey` now, which should include z3 libraries right in the jar.

**Comment by lemmy** [comment]
Does z3-turnkey mean that z3 and its deps are included in apalache.tgz?

**Comment by konnov** [comment]
Yes. The jar inside tgz contains the libraries:

```
$ jar tf mod-distribution/target/apalache-pkg-0.15.6-full.jar | grep -e '\.\(so\|dll\)'
native/windows-x86/libz3.dll
native/windows-x86/libz3java.dll
native/linux-amd64/libz3.so
native/linux-amd64/libz3java.so
native/windows-amd64/libz3.dll
native/windows-amd64/libz3java.dll
```

**Comment by lemmy** [comment]
That explains why apalache worked on gitpod despite the installation of `libz3-java` failing.

Btw. what about macOS x86 and arm64?

**Comment by konnov** [comment]
Works on my macOS x86, though z3 does not seem to work on M1's yet.

**Comment by lemmy** [comment]
I haven't tried it much yet, but one can re-locate a gitpod or codespace workspace with the push of a button to a locally running VSCode.  However, the TLA+ tools continue to be executed on the remote host.  Might be an option for those users who wish to work with Apalache on M1 for as long as z3-turnkey isn't compatible.

**Pull request closed without merging**
